### ISSUE TITLE
Gradient with custom props for labels and data only

### ISSUE THREAD

**Issue by maciz84** [apertureless/vue-chartjs-demo#2]
Hi Guys,

I am trying to add gradient to my chart which I can do as per numerous examples found here. However I am trying to have the gradient and the ability to just have the labels and dataset data as bindable properties.

I would like a reusable chart across my application and most of the examples have hard coded labels and datasets data properties. So in other words I have the code below but need to add the  color stops in it as I cannot add it in my component?

```import { Bar, mixins } from 'vue-chartjs';

export default {
    extends: Bar,
    mixins: [mixins.reactiveProp],
    props: ['chartData', 'options'],
    mounted() {
        this.renderChart(this.chartData, this.options);
    }
};

This examples [https://hackernoon.com/creating-stunning-charts-with-vue-js-and-chart-js-28af584adc0a]
works but it has hard coded values and want to send only the data and labels as props...if this makes sense

**Comment by apertureless** [comment]
Well you can then just pass in the data as props and for example use computed properties to "build" your data object with gradients.

btw. check out the main vue-chartjs repo or the [docs](http://vue-chartjs.org) there are a few examples.

**Comment by maciz84** [comment]
@apertureless thanks dude :)

**Comment by maciz84** [comment]
I know this issue is closed but I couldn’t find an example that suited my scenario. If you ever have time I would like to see a simple example as to understand what you meant by using computer properties to “build” my data object???
